# Generated by Django 6.0.4 on 2026-04-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klient_ismi', models.CharField(max_length=255)),
                ('mashina_raqami', models.CharField(max_length=20)),
                ('muammo', models.TextField()),
                ('usta_ismi', models.CharField(max_length=255)),
                ('narxi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markasi', models.CharField(max_length=255)),
                ('modeli', models.CharField(max_length=255)),
                ('kubaturasi', models.IntegerField(default=0)),
                ('rangi', models.CharField(max_length=255)),
                ('narxi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('qaysi_mashinaga', models.CharField(max_length=255)),
                ('zavod_kodi', models.CharField(max_length=50, unique=True)),
                ('narxi', models.IntegerField(default=0)),
                ('kafolati', models.IntegerField(default=0)),
            ],
        ),
    ]
