# Generated by Django 6.0.4 on 2026-04-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=255)),
                ('familiya', models.CharField(max_length=255)),
                ('sport_turi', models.CharField(max_length=255)),
                ('boyi', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vazni', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=255)),
                ('familiya', models.CharField(max_length=255)),
                ('tajribasi', models.IntegerField(default=0)),
                ('ixtisosligi', models.CharField(max_length=255)),
                ('oylik_maosh', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('sana', models.DateField()),
                ('mukofot_jamgarmasi', models.IntegerField(default=0)),
                ('manzili', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('manzili', models.CharField(max_length=255)),
                ('oylik_abonement_narxi', models.IntegerField(default=0)),
                ('ish_vaqti', models.CharField(max_length=255)),
            ],
        ),
    ]
