# Generated by Django 6.0.4 on 2026-04-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('muallif', models.CharField(max_length=255)),
                ('betlar_soni', models.IntegerField(default=0)),
                ('janri', models.CharField(max_length=255)),
                ('nashriyot', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('sana', models.DateField()),
                ('chipta_narxi', models.IntegerField(default=0)),
                ('mavzusi', models.CharField(max_length=255)),
                ('tashkilotchi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('mavzusi', models.CharField(max_length=255)),
                ('muallif', models.CharField(max_length=255)),
                ('qismlar_soni', models.IntegerField(default=1)),
                ('platforma', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('ijrochi', models.CharField(max_length=255)),
                ('janri', models.CharField(max_length=255)),
                ('davomiyligi', models.IntegerField(default=0)),
                ('yili', models.IntegerField(default=1)),
            ],
        ),
    ]
