# Generated by Django 6.0.4 on 2026-04-21 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=255)),
                ('familiyasi', models.CharField(max_length=255)),
                ('mutaxassisligi', models.CharField(max_length=100)),
                ('xona_raqami', models.IntegerField(unique=True)),
                ('tajribasi', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('dozasi', models.CharField(max_length=100)),
                ('turi', models.CharField(max_length=100)),
                ('muddati', models.CharField(max_length=100)),
                ('qollash_usuli', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=255)),
                ('familiyasi', models.CharField(max_length=255)),
                ('kasallik_tarixi', models.TextField()),
                ('qon_guruhi', models.CharField(max_length=10)),
                ('yoshi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('vaqt', models.TimeField()),
                ('shikoyati', models.TextField()),
                ('shifokor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tibiyot.doctor')),
                ('bemor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tibiyot.patient')),
            ],
        ),
    ]
