# Generated by Django 6.0.4 on 2026-04-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tibiyot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='xona_raqami',
            field=models.IntegerField(),
        ),
    ]
