# Generated by Django 6.0.4 on 2026-04-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uy_raqami', models.IntegerField(unique=True)),
                ('xonalar_soni', models.IntegerField()),
                ('maydoni', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qavat', models.IntegerField()),
                ('narxi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('qavatlar_soni', models.IntegerField()),
                ('qurilgan_yili', models.IntegerField()),
                ('manzili', models.CharField(max_length=255)),
                ('turi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maydoni', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('turi', models.CharField(max_length=100)),
                ('manzili', models.CharField(max_length=255)),
                ('kadastr_raqami', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
