# Generated by Django 6.0.4 on 2026-04-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uy_joy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='uy_raqami',
            field=models.IntegerField(),
        ),
    ]
