# Generated by Django 6.0.4 on 2026-04-21 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('tavsifi', models.TextField(blank=True, null=True)),
                ('rasm_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('familiya', models.CharField(max_length=20)),
                ('telefon', models.CharField(max_length=20)),
                ('manzili', models.TextField(blank=True, null=True)),
                ('jami_xaridi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kompaniya_nomi', models.CharField(max_length=150)),
                ('masul_shaxs', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('yetkazish_muddati', models.CharField(default='1 kun', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('umumiy_summa', models.IntegerField(default=0)),
                ('tolov_turi', models.CharField(max_length=50)),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savdo.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('kodi', models.IntegerField(default=0)),
                ('narxi', models.IntegerField(default=0)),
                ('miqdori', models.IntegerField(default=0)),
                ('ishlab_chiqaruvchi', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='savdo.category')),
            ],
        ),
    ]
