# Generated by Django 6.0.4 on 2026-04-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyiha_nomi', models.CharField(max_length=255)),
                ('xatolik_tavsifi', models.TextField()),
                ('jiddiylik_darajasi', models.CharField(max_length=255)),
                ('topilgan_sana', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend', models.CharField(max_length=255)),
                ('protsessor', models.CharField(max_length=255)),
                ('ram_hajmi', models.IntegerField(default=0)),
                ('xotira', models.CharField(default='GB', max_length=255)),
                ('narxi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('muddat', models.DateField()),
                ('byudjet', models.IntegerField(default=0)),
                ('masul_shaxs', models.CharField(max_length=255)),
                ('holati', models.CharField(default='yangi', max_length=255)),
            ],
        ),
    ]
