# Generated by Django 6.0.4 on 2026-04-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('tarkibi', models.TextField()),
                ('narxi', models.IntegerField(default=0)),
                ('kaloriyasi', models.IntegerField(default=0)),
                ('tayyorlanish_vaqti', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqami', models.IntegerField(default=0)),
                ('orinqlar_soni', models.IntegerField(default=0)),
                ('holati', models.BooleanField(default=False)),
                ('qavat', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=255)),
                ('familiya', models.CharField(max_length=255)),
                ('stol_raqamlari', models.CharField(max_length=255)),
                ('tajribasi', models.IntegerField(default=0)),
                ('reytingi', models.IntegerField(default=0)),
            ],
        ),
    ]
